### PR TITLE
[24.1] Backport JDK 23+26 upgrade changes to 24.1 release tree

### PR DESCRIPTION
**Pull request by jerboaa**
Backport https://github.com/oracle/graal/pull/9078

### CODE REVIEW

**Comment by jerboaa** [comment]
CI run with this: https://github.com/graalvm/mandrel/actions/runs/9660331969

**Comment by jerboaa** [comment]
> CI run with this: https://github.com/graalvm/mandrel/actions/runs/9660331969

Summary of test failures is as follows (some of them we saw during nightly CI testing of graal/master when JDK 23 was the latest JDK release):

* [Q IT Messaging1](https://github.com/graalvm/mandrel/actions/runs/9660331969/job/26647143380): quarkus-integration-test-kafka-oauth-keycloak native integration failure due to: https://github.com/quarkusio/quarkus/issues/39634. Known issue.
* [Q IT Data6](https://github.com/graalvm/mandrel/actions/runs/9660331969/job/26647142022): quarkus-integration-test-hibernate-search-orm-elasticsearch-outbox-polling fails due to a version parsing issue of 23-beta as reported in https://github.com/quarkusio/quarkus/issues/39664 (caused by this upstream awaitability issue: https://github.com/awaitility/awaitility/issues/277). Known issue.
* [Mandrel IT](https://github.com/graalvm/mandrel/actions/runs/9660331969/job/26647139157) test failures are:
  * `DynamicProxyConfigurationResources` related warnings. Tracked in https://github.com/Karm/mandrel-integration-tests/issues/261
  * AWT imageio test fails to generate images. Tracked in https://github.com/Karm/mandrel-integration-tests/issues/262

**Comment by jerboaa** [comment]
@zakkak Could you please take a look? This would unbreak the JDK 23-based builds from the release branch.

**Review by zakkak — CHANGES_REQUESTED** [review]
Thank you @jerboaa!

In general I am in favor of cherry picking the commits with the `-x` flag to make it easier to track backports back to the original commits but in this case the original PR consists of 44 commits...

So I am thinking that in this case maybe we could amend the commit message to include the commit messages and hashes of the backported commits and rebase? (skipping the empty automated ones)

Please let me know if you would like me to take this over.

**Comment by zakkak** [comment]
Futhermore, https://github.com/oracle/graal/pull/9078 is most probably going to be backported upstream as well so this is just an "early backport" for us to get testing working again, right?

**Comment by jerboaa** [comment]
> Futhermore, [oracle#9078](https://github.com/oracle/graal/pull/9078) is most probably going to be backported upstream as well so this is just an "early backport" for us to get testing working again, right?

Yes, it'll be an early backport.

>  In general I am in favor of cherry picking the commits with the -x flag to make it easier to track backports back to the original commits but in this case the original PR consists of 44 commits...
>
>So I am thinking that in this case maybe we could amend the commit message to include the commit messages and >hashes of the backported commits and rebase? (skipping the empty automated ones)

Wow, that seems like a bit of a waste of time in this case. I'm thinking of pushing this, then do `git revert <sha>` and merge the upstream changes once available.

>
> Please let me know if you would like me to take this over.

If you feel like it's worth going this route of cherry-picking 44 commits then yes, please, take it over.

**Comment by zakkak** [comment]
Closing in favor of #757

**Pull request closed without merging**
