### PR TITLE
Merge latest upstream (2024-12-20)

### PR DESCRIPTION
**Pull request by zakkak**
Includes 3 backports and a change in the github issue templates (which doesn't affect this repository)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Looks good.

**Comment by Karm** [comment]
Those backports are:

https://github.com/graalvm/graalvm-community-jdk21u/pull/33
https://github.com/graalvm/graalvm-community-jdk21u/pull/34
https://github.com/graalvm/graalvm-community-jdk21u/pull/35

**Comment by Karm** [comment]
Jenkins will pick up the change too...

**Comment by jerboaa** [comment]
The issue template PR upstream was: https://github.com/graalvm/graalvm-community-jdk21u/pull/27

**Pull request merged**
