### PR TITLE
CI: Switch to adoptium releases

### PR DESCRIPTION
**Pull request by zakkak**
Test runs:
* Windows: https://github.com/zakkak/mandrel/actions/runs/1445056442
* Linux: https://github.com/zakkak/mandrel/actions/runs/1445055981

### CODE REVIEW

**Review by jerboaa — COMMENTED** [review]
Is this a known issue on Windows?
```
 Building com.oracle.svm.native.libchelper_amd64 with Ninja... [dependency NINJA_SYNTAX updated]
JvmFuncsFallbacksBuildTask svm-jvmfuncs-fallback-builder... [D:\a\mandrel\mandrel\mandrel\substratevm\mxbuild\svm-jvmfuncs-fallback-builder\src_gen\JvmFuncsFallbacks.c does not exist]
```

**Comment by zakkak** [comment]
> Is this a known issue on Windows?
> 
> ```
>  Building com.oracle.svm.native.libchelper_amd64 with Ninja... [dependency NINJA_SYNTAX updated]
> JvmFuncsFallbacksBuildTask svm-jvmfuncs-fallback-builder... [D:\a\mandrel\mandrel\mandrel\substratevm\mxbuild\svm-jvmfuncs-fallback-builder\src_gen\JvmFuncsFallbacks.c does not exist]
> ```

No, this is a regression, it is failing to find the static libs (my powershell foo is to blame). Working on it...

**Comment by jerboaa** [comment]
> > Is this a known issue on Windows?
> > ```
> >  Building com.oracle.svm.native.libchelper_amd64 with Ninja... [dependency NINJA_SYNTAX updated]
> > JvmFuncsFallbacksBuildTask svm-jvmfuncs-fallback-builder... [D:\a\mandrel\mandrel\mandrel\substratevm\mxbuild\svm-jvmfuncs-fallback-builder\src_gen\JvmFuncsFallbacks.c does not exist]
> > ```
> 
> No, this is a regression, it is failing to find the static libs (my powershell foo is to blame). Working on it...

I'm sure your powershell foo is a lot better than mine :-P

**Comment by zakkak** [comment]
New windows run: https://github.com/zakkak/mandrel/actions/runs/1445767907

**Review by jerboaa — APPROVED** [review]
Test are passing. Ship it!

**Pull request merged**
