### PR TITLE
Clear lower half of two-slot value when upper half is not live

### PR DESCRIPTION
**Pull request by zakkak**
Backport of: https://github.com/oracle/graal/commit/929dde28d8ba99b3d044be2b6fb86ce1625a2286

### CODE REVIEW

**Comment by jerboaa** [comment]
This is a fix for: https://github.com/oracle/graal/issues/2735 (i.e. fixes tests when running with assertions on). @zakkak Isn't this affecting `20.1` too?

**Comment by jerboaa** [comment]
See also: https://github.com/graalvm/mandrel/pull/87

**Comment by jerboaa** [comment]
Fixes https://github.com/graalvm/mandrel/issues/111

**Comment by zakkak** [comment]
Oh I totally forgot to add all the info :/
Thanks @jerboaa 

Yes this affects 20.1 but we said we don't want to backport it there unless we get a ticket about it.

**Review by jerboaa — APPROVED** [review]
Looks good.

**Comment by jerboaa** [comment]
> Yes this affects 20.1 but we said we don't want to backport it there unless we get a ticket about it.

OK.

**Comment by jerboaa** [comment]
> > Yes this affects 20.1 but we said we don't want to backport it there unless we get a ticket about it.
> 
> OK.

However, I'd prefer we ran tests with assertions enabled, even for 20.1. I think we already do? The fix should be pretty harmless and it might help us detect a real issue. This false assertion might hide something else.

**Comment by zakkak** [comment]
> However, I'd prefer we ran tests with assertions enabled, even for 20.1. I think we already do? 

Correct. We do test 20.1 with assertions enabled (and that's why we see the CI failing https://github.com/graalvm/mandrel/runs/1286947215?check_suite_focus=true) 

> The fix should be pretty harmless and it might help us detect a real issue. This false assertion might hide something else.

I wouldn't say this is a false assertion. The fix includes clearing an extra slot not just removing the assertion.

+1 on backporting it to 20.1 as well

**Pull request merged**
