### PR TITLE
[24.0] Sync with upstream for July 2024 CPU

### PR DESCRIPTION
**Pull request by zakkak**
Sync with upstream 'oracle/release/graal-vm/24.0' for July 2024 CPU
    
Merged cleanly except for:
    
1. https://github.com/oracle/graal/commit/7c9303233696ed1f2a09f366205e241cdf6104c4 which conflicts with our earlier backport in https://github.com/graalvm/mandrel/pull/722. To deviate as little as possible from upstream I dropped our backport in favour of the upstream one.
    
2. The suite files were updated to match the Mandrel version scheme, i.e. the version is set to 24.0.2.0 instead of 24.0.2, and the Release value is set to False.

### CODE REVIEW

**Comment by zakkak** [comment]
Build fails with:

```
Exception in thread "main" java.lang.IllegalArgumentException: Version should be of the form MAJOR.MINOR.PATCH not 7.4.1.1
	at MxVersion.<init>(build.java:1529)
	at Mx.<init>(build.java:926)
	at build.main(build.java:58)
```

Looking

**Comment by zakkak** [comment]
CI failure is:

```
Error:  Failures: 
Error:    DebugSymbolsTest.debugSymbolsQuarkus:306 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.DebugSymbolsTest/debugSymbolsQuarkus/build-and-run.log and check these offending lines: 
WARNING: Duplicate name in Manifest: Specification-Version.
WARNING: Duplicate name in Manifest: Implementation-Version. ==> expected: <true> but was: <false>
Error:    JFRTest.jfrPerfTest:185->jfrPerfTestRun:234 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.JFRTest/jfrPerfTest/build-and-run.log and check these offending lines: 
WARNING: Duplicate name in Manifest: Specification-Version.
WARNING: Duplicate name in Manifest: Implementation-Version. ==> expected: <true> but was: <false>
Error:    RuntimesSmokeTest.quarkusFullMicroProfile:200->testRuntime:156 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusFullMicroProfile/build-and-run.log and check these offending lines: 
WARNING: Duplicate name in Manifest: Specification-Version.
WARNING: Duplicate name in Manifest: Implementation-Version. ==> expected: <true> but was: <false>
[INFO] 
```

It's irrelevant to this sync. I will backport https://github.com/graalvm/mandrel-packaging/pull/435 to `24.0` to fix it.

Update: The backport PR is https://github.com/graalvm/mandrel-packaging/pull/438

**Comment by jerboaa** [comment]
@zakkak Could you please trigger another CI run. The Mandrel IT failure should be gone with the backport.

**Review by jerboaa — APPROVED** [review]
This seems OK. Please trigger a CI run which should be clean before we merge.

**Comment by zakkak** [comment]
maven-tooling failed due to:

```
Error during callback: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}
```

Rerunning only the corresponding batch of tests, should take ~1 hour

**Comment by Karm** [comment]
@zakkak 

https://github.com/quarkusio/quarkus/issues/40960

:(

**Comment by jerboaa** [comment]
Looks good now.

**Comment by Karm** [comment]
Thx.

**Pull request merged**
