### PR TITLE
[24.1] Backport https://github.com/oracle/graal/pull/9078

### PR DESCRIPTION
**Pull request by zakkak**
Backports the following commits:

ceaac5f6f8009c05a78a756c2e9fa1370691c3b2 Automatic merge of master into galahad
f1a2d954b2ea8b67b3b06c85e30e1d1dfcd6493f Automatic merge of master into galahad
59a170e007341f4eb74047fa27dd555377d95d3f compiler: adopt "JDK-8332826: Make hashCode methods in ArraysSupport friendlier" 
2b2754d3d45b2580e07dd482f68463e306becd3c svm: adopt "JDK-8331189: Implementation of Scoped Values (Third Preview)" 
07d3bc2503303731fe3717e70626af8903caf155 update galahad-jdk 
90def08290974ffffc79c4c9577f8896bfe7d2bd compiler: no more JDK 21 style gate in galahad 
2a04ddeebfbfbe97cee550a601a921e5412c9602 Automatic merge of master into galahad 
d2f6535c41cc04a4e78bfc9a8c17515eadc7d54a Automatic merge of master into galahad 
e1771d1dc2128dde2cf813e86341cc62757c6402 Automatic merge of master into galahad 
268aa8d94d0c9c33c1f8e6433ec280500deae1d5 reduce galahad gate to bare minimum 
3bd87540c4bf81f13885fdb34632866b9199a697 [JDK-8333292] Fix libgraal build broken by JDK-8331189. 
188f35a8cf2493e6132a7d406b5dd13dcd5c96ae Fix libgraal build broken by JDK-8331877. 
95415adb721ff438aed193c9f138de3f1802c343 [JDK-8333362] Fix libgraal build broken by JDK-8331877. 
3fbd87a25953b25441bac00a66fb3ca459c18dd8 Automatic merge of master into galahad 
93923e4454c8273669907ccb72a3c6af54fca0b4 Automatic merge of master into galahad 
a29b4da35d60dbd4852a4a272ec0e6bb2ec0283d Automatic merge of master into galahad 
ee5cef44f0064d1daf623085092b14b5ca291dbd Automatic merge of master into galahad 
8b40a6a9c96726db8c2bdbb58376cec5ea5001ac Automatic merge of master into galahad 
4d34880dc0676a975af0954357fde2782eff6bb7 Merge master into galahad 
414d874be3af1a21a3c8ebfd9cbd163b985a0a68 [GR-54472] Resolve merge conflits. 
78ec64e7517491dc296903d30d247398248853d4 Automatic merge of master into galahad 
768bab8ead8824a93da337d9547c647b6232dcfa Automatic merge of master into galahad 
ca7c3ca212ad0a431c9e2d7b2cc2de16f863eaff Automatic merge of master into galahad 
4ce7fe8a1963d27240def2514fbd1e3e52417526 Automatic merge of master into galahad 
02a83e93dbb70349d5bd1f2a94702f0e209c6fc0 Automatic merge of master into galahad 
b6f336516c0bb6cba0a7089cd2f1c934cff61530 Automatic merge of master into galahad 
859ea9d815684a210545e0895a93067d8d106f87 Fix incorrect resolution of merge conflicts for VectorizedHashCodeTest 
8f4c2145361fdd57a7db90181f05a829c08eecc3 Automatic merge of master into galahad 
bdedb09ebdd60f7b0b91d1c5b416dae78aa85bec Automatic merge of master into galahad 
103dbcaf104957bf24b3c88de5d2f24f462d0270 Automatic merge of master into galahad

Supersedes https://github.com/graalvm/mandrel/pull/751

### CODE REVIEW

**Comment by zakkak** [comment]
FTR

> If you feel like it's worth going this route of cherry-picking 44 commits then yes, please, take it over.

I used the following command and amended the original commit:

```
curl -s https://api.github.com/repos/oracle/graal/pulls/9078/commits | jq -r '.[] | "\(.sha) \(.commit.message)"'
``` 

@jerboaa I had to create a new PR because I couldn't push to your branch.

**Comment by zakkak** [comment]
I went ahead and added the Mandrel readme, patched the version to match the Mandrel scheme and added workflows.

As with previous releases, moving forward we should rebase this branch on top of https://github.com/oracle/graal/tree/release/graal-vm/24.1 and force push until the first 24.1.x release.

**Comment by jerboaa** [comment]
> As with previous releases, moving forward we should rebase this branch on top of https://github.com/oracle/graal/tree/release/graal-vm/24.1 and force push until the first 24.1.x release.

I thought we do merges now and no longer force-push due to branch protections?

**Review by jerboaa — APPROVED** [review]
OK.

Lots of test failures that look like this:
```
 Caused by: java.lang.NoSuchMethodError: jakarta.ws.rs.ext.Providers.getContextResolver(java.lang.Class, jakarta.ws.rs.core.MediaType)
	at jdk.proxy4/jdk.proxy4.$Proxy/sfa608265.$getMethod(Unknown Source)
	... 38 more
```

But that's for a different patch.

**Comment by zakkak** [comment]
> I thought we do merges now and no longer force-push due to branch protections?

No, we can still force push as long as the repository is under the `oracle` organization. I added an exception for `mandrel/24.1` in https://github.com/graalvm/mandrel/settings/branches

**Comment by zakkak** [comment]
> OK.
> 
> Lots of test failures that look like this:
> 
> ```
>  Caused by: java.lang.NoSuchMethodError: jakarta.ws.rs.ext.Providers.getContextResolver(java.lang.Class, jakarta.ws.rs.core.MediaType)
> 	at jdk.proxy4/jdk.proxy4.$Proxy/sfa608265.$getMethod(Unknown Source)
> 	... 38 more
> ```

That would be https://github.com/quarkusio/quarkus/issues/41283, which should be fixed by https://github.com/oracle/graal/pull/9184 (waiting for CI to confirm), so we would need to backport https://github.com/oracle/graal/pull/9184 as well. Tracked in https://github.com/graalvm/mandrel/issues/758

**Comment by zakkak** [comment]
This backport has been dropped in favor of the upstream https://github.com/oracle/graal/pull/9247

**Pull request merged**
