### PR TITLE
Synchronize with upstream 23.1 branch

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by zakkak** [comment]
mandrel-IT failure looks like a timeout waiting for GDB (I will rerun it)

Looking into kafka-oauth-keycloak issue in the meantime

**Comment by zakkak** [comment]
> Looking into kafka-oauth-keycloak issue in the meantime

This is [a Quarkus issue](https://github.com/quarkusio/quarkus/issues/36653).

**Review by jerboaa — APPROVED** [review]
Seems OK to me. Any local patches that we have dropped?

**Comment by zakkak** [comment]
> Seems OK to me. Any local patches that we have dropped?

Not exactly dropped but any backports we have done before upstream are now in except for https://github.com/graalvm/mandrel/pull/569 which is not yet backported upstream (see https://github.com/oracle/graal/pull/7574)

**Pull request merged**
