### PR TITLE
Open PR instead of silently pushing changes to 20.1

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by galderz** [comment]
Looks good. If we're going to add PRs, then we might want to reduce the frequency, say once a day?

**Comment by galderz** [comment]
Also, we need to see the interaction of this with the `on` set up. I also set up a sync when a commit is pushed to either `master` or `20.1`... so that might need reworking a bit.

**Comment by zakkak** [comment]
> Looks good. If we're going to add PRs, then we might want to reduce the frequency, say once a day?

Yes, once a day sounds reasonable to me.

> Also, we need to see the interaction of this with the `on` set up. I also set up a sync when a commit is pushed to either `master` or `20.1`... so that might need reworking a bit.

Sorry if I missed that, but what's the reasoning behind the sync on push?

**Comment by galderz** [comment]
> Sorry if I missed that, but what's the reasoning behind the sync on push?

I mostly used that to verify that an update to the actions triggered the github action. In theory you're developing against `master` or `20.1`. When you push a new change, it'd automatically trigger a merge with the upstream master/20.1 branches. Otherwise you have wait N time to see your changes against the latest upstream.

**Comment by galderz** [comment]
That's why maybe we need separate actions for master vs 20.1. For master it makes sense to have it on every push (to see if actions get updated right), but for 20.1 only periodic, once a day and then create a PR.

**Comment by zakkak** [comment]
> > Sorry if I missed that, but what's the reasoning behind the sync on push?
> 
> I mostly used that to verify that an update to the actions triggered the github action. In theory you're developing against `master` or `20.1`. When you push a new change, it'd automatically trigger a merge with the upstream master/20.1 branches. Otherwise you have wait N time to see your changes against the latest upstream.

I think Working `N` time behind upstream is OK. I would only like to be in total sync with upstream if I was to create a PR on upstream, but for that I wouldn't go through `graalvm/mandrel` anyway. 

> That's why maybe we need separate actions for master vs 20.1. For master it makes sense to have it on every push (to see if actions get updated right), but for 20.1 only periodic, once a day and then create a PR.

We can have an action running on push only when `.github/workflows` gets touched.

**Comment by galderz** [comment]
> We can have an action running on push only when .github/workflows gets touched.

That's a good idea :)

**Pull request merged**
