### PR TITLE
CI: Don't use commit hash as version

### PR DESCRIPTION
**Pull request by zakkak**
Avoids https://github.com/graalvm/mandrel/issues/218 in CI.

### CODE REVIEW

**Comment by zakkak** [comment]
Note I prefer merging https://github.com/graalvm/mandrel-packaging/pull/106 (which will solve the issue for all branches at once) instead of this (and similar) PR(s).

**Review by jerboaa — APPROVED** [review]
Looks OK.

**Comment by jerboaa** [comment]
why is this still a draft?

**Comment by zakkak** [comment]
Because I prefer merging and using https://github.com/graalvm/mandrel-packaging/pull/106 instead

(see https://github.com/graalvm/mandrel/pull/221#issuecomment-788382039)

**Comment by jerboaa** [comment]
ugh, sorry. Thanks.

**Comment by jerboaa** [comment]
Closing this one as graalvm/mandrel-packaging#106 got merged.

**Pull request closed without merging**
