### PR TITLE
Documentation, native-image depends on libffi-devel

### PR DESCRIPTION
**Pull request by Karm**
Fixes issue #30

### CODE REVIEW

**Comment by zakkak** [comment]
Let's discuss this in #25

**Comment by jerboaa** [comment]
+1 on `README-Mandrel.md`

**Comment by galderz** [comment]
@jerboaa See discussion in #25, @zakkak is proposing a wiki instead of a README. I'd favour wiki.

**Comment by jerboaa** [comment]
@galderz To me it would make more sense for the rather static-ish doc to be in a `README-mandrel.md` simple because it would be part of the source (and potentially a binary release).

**Comment by Karm** [comment]
@galderz    I would like to see this kind of compilation/sys dependencies in Mandrel-README.md.  Amended both #32  and #33 .  The reasoning is that Wiki is not a part of the code you pulled and it follows what Graal does (also not using github wiki).

**Pull request closed without merging**
