### PR TITLE
[CI] Enable non time sensitive performance regression checks

### PR DESCRIPTION
**Pull request by zakkak**
Made possible with
https://github.com/Karm/mandrel-integration-tests/pull/205

### CODE REVIEW

**Comment by zakkak** [comment]
Being tested in https://github.com/zakkak/mandrel/actions/runs/6402807992 and https://github.com/zakkak/mandrel/actions/runs/6402807991

**Comment by zakkak** [comment]
Windows job "[Q main M 23.1 windows](https://github.com/zakkak/mandrel/actions/runs/6402807992/job/17380825184#logs)" [fails with](https://github.com/zakkak/mandrel/actions/runs/6402807992/job/17380825184):

```
Application QUARKUS_FULL_MICROPROFILE in mode none executable size  is 76532 kB, which is over 75000 kB threshold by 2%.
 ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:162)
	at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:192)
```

@Karm do you see this in your 23.1 runs as well?

**Comment by zakkak** [comment]
> @Karm do you see this in your 23.1 runs as well?

@Karm can you please have a look at this?

**Comment by zakkak** [comment]
Rebased. Being tested in

* https://github.com/zakkak/mandrel/actions/runs/6846862473 
* https://github.com/zakkak/mandrel/actions/runs/6846862478

**Comment by Karm** [comment]
@zakkak Loading context...

**Comment by Karm** [comment]
@zakkak 


Linux amd64
===========

| Quarkus       | Mandrel               | Executable size |
| ------------- | --------------------- | --------------- |
| 3.1.3.Final   | java17-22.3.4.0-Final | 68053 Kb        |
| 2.7.7.Final   | java17-21.3.6.0-Final | 68558 Kb        |
| 3.4.3         | java17-23.0.2.1-Final | 71954 Kb        |
| 3.5.1         | java21-23.1.1.0-Final | 76647 Kb        |



Linux aarch64
=============

| Quarkus       | Mandrel               | Executable size |
| ------------- | --------------------- | --------------- |
| 3.1.3.Final   | java17-22.3.4.0-Final | 68525 Kb        |
| 2.7.7.Final   | java17-21.3.6.0-Final | 68075 Kb        |
| 3.4.3         | java17-23.0.2.1-Final | 70063 Kb        |
| 3.5.1         | java21-23.1.1.0-Final | 74159 Kb        |



Windows amd64
=============

| Quarkus       | Mandrel               | Executable size |
| ------------- | --------------------- | --------------- |
| 3.1.3.Final   | java17-22.3.4.0-Final | 68780 Kb        |
| 2.7.7.Final   | java17-21.3.6.0-Final | 70562 Kb        |
| 3.4.3         | java17-23.0.2.1-Final | 72760 Kb        |
| 3.5.1         | java21-23.1.1.0-Final | 76652 Kb        |



I think this is sane and what we've got now.

**Comment by zakkak** [comment]
Being tested in https://github.com/zakkak/mandrel/actions/runs/6944009708 and https://github.com/zakkak/mandrel/actions/runs/6944009711

**Pull request merged**
