### PR TITLE
Update CI to match that of quarkus

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by Karm** [comment]
@zakkak @galderz @jerboaa  One note about `NATIVE_TEST_MAVEN_OPTS` property.  Don't you think we should be adding `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11` or perhaps better `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:latest`?   

I am talking about https://github.com/quarkusio/quarkus/blob/master/.github/workflows/native-cron-build.yml#L57

**Comment by Karm** [comment]
Not sure if this is the place though as it divorces the code in this repo from the Mandrel it compiles with.

**Comment by Karm** [comment]
Hmm, might need fixing or exclusions though:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus - Integration Tests 1.5.1.Final:
[INFO] 
[INFO] Quarkus - Integration Tests ........................ SUCCESS [  4.439 s]
[INFO] Quarkus - Integration Tests - Funqy Amazon Lambda .. SUCCESS [02:46 min]
[INFO] Quarkus - Integration Tests - Class tranformer ..... SUCCESS [  0.061 s]
[INFO] Quarkus - Integration Tests - Class tranformer - Deployment SUCCESS [  4.840 s]
[INFO] Quarkus - Integration Tests - Class tranformer - Runtime SUCCESS [  2.193 s]
[INFO] Quarkus - Integration Tests - Shared library ....... SUCCESS [  0.125 s]
[INFO] Quarkus - Integration Tests - Hibernate Validator .. SUCCESS [02:44 min]
[INFO] Quarkus - Integration Tests - Common JPA entities .. SUCCESS [  0.398 s]
[INFO] Quarkus - Integration Tests - Infinispan Client .... SUCCESS [03:39 min]
[INFO] Quarkus - Integration Tests - Infinispan Embedded .. SUCCESS [04:11 min]
[INFO] Quarkus - Integration Tests - Main ................. SUCCESS [08:43 min]
[INFO] Quarkus - Integration Tests - Kafka ................ SUCCESS [04:34 min]
[INFO] Quarkus - Integration Tests - Kafka Streams ........ SUCCESS [03:26 min]
[INFO] Quarkus - Integration Tests - JPA .................. SUCCESS [02:50 min]
[INFO] Quarkus - Integration Tests - JPA - Derby .......... SUCCESS [02:56 min]
[INFO] Quarkus - Integration Tests - JPA - PostgreSQL ..... SUCCESS [03:08 min]
[INFO] Quarkus - Integration Tests - Vault ................ SUCCESS [ 56.618 s]
[INFO] Quarkus - Integration Tests - Vault Agroal ......... SUCCESS [ 25.446 s]
[INFO] Quarkus - Integration Tests - Vault App ............ FAILURE [  4.893 s]
[INFO] Quarkus - Integration Tests - JPA - MariaDB ........ SUCCESS [03:28 min]
[INFO] Quarkus - Integration Tests - JPA - H2 ............. SUCCESS [02:38 min]
[INFO] Quarkus - Integration Tests - JPA - MSSQL .......... SUCCESS [03:56 min]
[INFO] Quarkus - Integration Tests - JPA - MySQL .......... SUCCESS [03:50 min]
[INFO] Quarkus - Integration Tests - Hibernate ORM with Panache FAILURE [ 32.997 s]
[INFO] Quarkus - Integration Tests - Hibernate ORM REST Data with Panache SUCCESS [03:44 min]
[INFO] Quarkus - Integration Tests - Hibernate ORM with Panache and Kotlin SUCCESS [04:02 min]
[INFO] Quarkus - Integration Tests - Hibernate Search + Elasticsearch FAILURE [ 43.767 s]
[INFO] Quarkus - Integration Tests - Hibernate - Multitenancy FAILURE [ 38.683 s]
[INFO] Quarkus - Integration Tests - Vert.x HTTP .......... SUCCESS [02:38 min]
[INFO] Quarkus - Integration Tests - Vert.x ............... SUCCESS [02:33 min]
[INFO] Quarkus - Integration Tests - Spring DI ............ SUCCESS [02:25 min]
[INFO] Quarkus - Integration Tests - Spring Web ........... SUCCESS [03:28 min]
[INFO] Quarkus - Integration Tests - Spring Data JPA ...... FAILURE [ 32.116 s]
[INFO] Quarkus - Integration Tests - Spring Boot properties SUCCESS [02:12 min]
[INFO] Quarkus - Integration Tests - Spring Cloud Config Client SUCCESS [02:49 min]
[INFO] Quarkus - Integration Tests - JPA - Infinispan Cache SUCCESS [02:57 min]
[INFO] Quarkus - Integration Tests - Elytron Security ..... SUCCESS [02:32 min]
[INFO] Quarkus - Integration Tests - Elytron Security OAuth2 SUCCESS [02:24 min]
[INFO] Quarkus - Integration Tests - Elytron RESTEasy ..... SUCCESS [02:04 min]
[INFO] Quarkus - Integration Tests - Elytron Undertow ..... SUCCESS [02:26 min]
[INFO] Quarkus - Integration Tests - Flyway ............... SUCCESS [02:39 min]
[INFO] Quarkus - Integration Tests - Liquibase ............ SUCCESS [05:02 min]
[INFO] Quarkus - Integration Tests - OpenID Connect Adapter SUCCESS [04:31 min]
[INFO] Quarkus - Integration Tests - OpenID Connect Adapter Code Flow SUCCESS [05:41 min]
[INFO] Quarkus - Integration Tests - Multi-Tenant OpenID Connect Adapter SUCCESS [05:22 min]
[INFO] Quarkus - Integration Tests - Keycloak Policy Enforcer FAILURE [01:09 min]
[INFO] Quarkus - Integration Tests - Reactive Pg Client ... SUCCESS [02:58 min]
[INFO] Quarkus - Integration Tests - Reactive MySQL Client  SUCCESS [03:06 min]
[INFO] Quarkus - Integration Tests - Amazon Services ...... SUCCESS [07:46 min]
[INFO] Quarkus - Integration Tests - Test Extension Native Tests FAILURE [  3.211 s]
[INFO] Quarkus - Integration Tests - Amazon Lambda ........ SUCCESS [01:29 min]
[INFO] Quarkus - Integration Tests - Amazon Lambda Stream Handler SUCCESS [01:15 min]
[INFO] Quarkus - Integration Tests - Amazon Lambda HTTP ... FAILURE [ 28.427 s]
[INFO] Quarkus - Integration Tests - Amazon Lambda HTTP RESTEasy SUCCESS [02:30 min]
[INFO] Quarkus - Integration Tests - Container Image - Parent SUCCESS [  0.016 s]
[INFO] Quarkus - Integration Tests - Container Image - Invoker SUCCESS [02:13 min]
[INFO] Quarkus - Integration Tests - Container Image - Standard SUCCESS [  7.007 s]
[INFO] Quarkus - Integration Tests - OptaPlanner Jackson .. SUCCESS [03:06 min]
[INFO] Quarkus - Integration Tests - OptaPlanner JSON-B ... SUCCESS [03:16 min]
[INFO] Quarkus - Integration Tests - Kubernetes - Parent .. SUCCESS [  0.015 s]
[INFO] Quarkus - Integration Tests - Kubernetes - Invoker . SUCCESS [ 55.798 s]
[INFO] Quarkus - Integration Tests - Kubernetes - Standard  SUCCESS [01:03 min]
[INFO] Quarkus - Integration Tests - Kubernetes Client .... SUCCESS [05:08 min]
[INFO] Quarkus - Integration Tests - Apache Tika .......... SUCCESS [03:40 min]
[INFO] Quarkus - Integration Tests - Neo4j ................ SUCCESS [03:11 min]
[INFO] Quarkus - Integration Tests - MongoDB Client ....... SUCCESS [02:39 min]
[INFO] Quarkus - Integration Tests - Jackson .............. SUCCESS [01:57 min]
[INFO] Quarkus - Integration Tests - JSON-B ............... SUCCESS [01:46 min]
[INFO] Quarkus - Integration Tests - RESTEasy Jackson ..... SUCCESS [02:21 min]
[INFO] Quarkus - Integration Tests - RESTEasy Mutiny ...... SUCCESS [02:32 min]
[INFO] Quarkus - Integration Tests - JGit ................. SUCCESS [03:11 min]
[INFO] Quarkus - Integration Tests - JSch ................. SUCCESS [02:30 min]
[INFO] Quarkus - Integration Tests - Virtual Http ......... SUCCESS [02:21 min]
[INFO] Quarkus - Integration Tests - Virtual Http Resteasy Standalone FAILURE [  6.966 s]
[INFO] Quarkus - Integration Tests - Artemis - Core ....... SUCCESS [02:42 min]
[INFO] Quarkus - Integration Tests - Artemis - JMS ........ SUCCESS [02:49 min]
[INFO] Quarkus - Integration Tests - Maven tooling ........ SUCCESS [03:28 min]
[INFO] Quarkus - Integration Tests - Scala ................ SUCCESS [01:09 min]
[INFO] Quarkus - Integration Tests - Kotlin ............... SUCCESS [01:08 min]
[INFO] Quarkus - Integration Tests - MongoDB Panache ...... SUCCESS [03:43 min]
[INFO] Quarkus - Integration Tests - Narayana STM ......... SUCCESS [02:05 min]
[INFO] Quarkus - Integration Tests - Narayana JTA CDI ..... SUCCESS [01:06 min]
[INFO] Quarkus - Integration Tests - Elytron Security JDBC  SUCCESS [02:53 min]
[INFO] Quarkus - Integration Tests - Elytron Security LDAP  SUCCESS [02:46 min]
[INFO] Quarkus - Integration Tests - Vert.x GraphQL ....... SUCCESS [02:34 min]
[INFO] Quarkus - Integration Tests - SmallRye GraphQL ..... SUCCESS [02:15 min]
[INFO] Quarkus - Integration Tests - JPA without entities . SUCCESS [01:58 min]
[INFO] Quarkus - Integration Tests - Quartz ............... SUCCESS [03:08 min]
[INFO] Quarkus - Integration Tests - Logging - GELF ....... SUCCESS [02:24 min]
[INFO] Quarkus - Integration Tests - Cache ................ SUCCESS [04:14 min]
[INFO] Quarkus - Integration Tests - Qute ................. FAILURE [ 32.347 s]
[INFO] Quarkus - Integration Tests - Bootstrap Config - Extension SUCCESS [  0.012 s]
[INFO] Quarkus - Integration Tests - Bootstrap Config - Extension - Runtime SUCCESS [  0.087 s]
[INFO] Quarkus - Integration Tests - Bootstrap Config - Extension - Deployment SUCCESS [  0.084 s]
[INFO] Quarkus - Integration Tests - Bootstrap Config ..... SUCCESS [  0.009 s]
[INFO] Quarkus - Integration Tests - Bootstrap Config - Application SUCCESS [01:38 min]
[INFO] Quarkus - Integration Tests - InjectMock ........... SUCCESS [  6.413 s]
[INFO] Quarkus - Integration Tests - Reactive Messaging - AMQP SUCCESS [02:41 min]
[INFO] Quarkus - Integration Tests - REST client .......... SUCCESS [01:58 min]
[INFO] Quarkus - Integration Tests - Packaging ............ SUCCESS [  2.895 s]
[INFO] Quarkus - Integration Tests - Simple with space .... SUCCESS [01:31 min]
[INFO] Quarkus - Integration Tests - Consul - Config ...... SUCCESS [02:45 min]
[INFO] Quarkus - Integration Tests - Picocli .............. SUCCESS [ 18.331 s]
[INFO] Quarkus - Integration Tests - Picocli Native ....... SUCCESS [01:57 min]
[INFO] Quarkus - Integration Tests - Dev Mode ............. SUCCESS [ 10.915 s]
[INFO] Quarkus - Integration Tests - gRPC - Plain Text .... SUCCESS [03:27 min]
[INFO] Quarkus - Integration Tests - gRPC - TLS ........... SUCCESS [02:45 min]
[INFO] Quarkus - Integration Tests - gRPC - TLS with mutual auth SUCCESS [02:56 min]
[INFO] Quarkus - Integration Tests - gRPC - Streaming ..... SUCCESS [02:29 min]
[INFO] Quarkus - Integration Tests - gRPC - Interceptors .. SUCCESS [02:53 min]
[INFO] Quarkus - Integration Tests - gRPC - Proto v2 ...... SUCCESS [02:59 min]
[INFO] Quarkus - Integration Tests - gRPC - Health ........ SUCCESS [02:09 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:13 h
[INFO] Finished at: 2020-06-29T17:05:43+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by zakkak** [comment]
> @zakkak @galderz @jerboaa One note about `NATIVE_TEST_MAVEN_OPTS` property. Don't you think we should be adding `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11` or perhaps better `-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:latest`?
> 
> I am talking about https://github.com/quarkusio/quarkus/blob/master/.github/workflows/native-cron-build.yml#L57

I agree that we need a way to test our images, but this is not the place. Here we need to test the latest code on the branch.

**Comment by Karm** [comment]
@zakkak I will use Jenkins for that.

**Comment by zakkak** [comment]
> Hmm, might need fixing or exclusions though:
>  

@Karm where is this from? 1.5.1 is expected to fail with this test suit, this is only compatible with > 1.6.0

**Comment by Karm** [comment]
Ah, right. It should have checked out 1.6 branch; but it went for the latest tag. Gonna change to the 1.6  branch.

**Comment by zakkak** [comment]
Ourr workflow currently gets the latest available tag (which currently is 1.6.0.CR1 at the moment) and the master branch. Unfortunately it's not easy to test against multiple versions with the same workflow. There has been some discussions on this but still nothing in place https://groups.google.com/forum/#!searchin/quarkus-dev/zakkak%7Csort:date/quarkus-dev/_KZe1ydg4C0/97xkqB9dCAAJ

**Pull request merged**
