### PR TITLE
[CI] Add weekly runs testing Mandrel builds based on JDK 22

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]

**Comment by zakkak** [comment]
Adoptium's API seems not updated yet:

```
Run curl -sL https://api.adoptium.net/v3/binary/latest/22/ea/linux/x64/jdk/hotspot/normal/eclipse -o jdk.tar.gz
tar: This does not look like a tar archive
```

**Comment by jerboaa** [comment]
> Adoptium's API seems not updated yet:
> 
> ```
> Run curl -sL https://api.adoptium.net/v3/binary/latest/22/ea/linux/x64/jdk/hotspot/normal/eclipse -o jdk.tar.gz
> tar: This does not look like a tar archive
> ```

I'll open an issue.

**Comment by zakkak** [comment]
> I'll open an issue.

@jerboaa I've done it https://github.com/adoptium/api.adoptium.net/issues/720

**Comment by jerboaa** [comment]
> > I'll open an issue.
> 
> @jerboaa I've done it [adoptium/api.adoptium.net#720](https://github.com/adoptium/api.adoptium.net/issues/720)

I see. Should be in the API. I'll close as duplicate.

**Comment by zakkak** [comment]
[API issue](https://github.com/adoptium/api.adoptium.net/issues/720) is now fixed. Re-running failed jobs.

**Pull request merged**
