### PR TITLE
2024-03-13 backports 21 sync

### PR DESCRIPTION
**Pull request by zakkak**
- Minor simplifications and cleanups.
- Change code lifecycle.
- For JIT compiled code that is on the stack, only walk the tether.
- [GR-50682] Quarkus fails even if class loader disabled.
- Remove Heap.allowPageSizeMismatch().
- Provide a method to set the physical memory size.
- GR-50494 : release GraalVM 23.1.2
- introduce ReportFatalErroronOutOfMemoryError
- Mark all killed XMM registers as @Temp in AMD64SHA256AVX2Op.
- Add memory barrier to HeapImpl.getAllClasses().
- Improve crash log.
- New dev cycle GraalVM 23.1.3
- Create lambda names format consistent with the JDK lambda names format.
- clean up
- style fixes
- fix debug section alignment which can lead to corrupt debug info
- Constant fold reflection lookups in sun.nio.ch.Reflect
- Fix style issues
- Create additional artifacts only on successful build.
- Only use -H:Path validation in non-bundle mode
- Explain reasoning as comment
- Fix Thread.getStackTrace() right after Thread.start().
- update JVMCI to 23.1-b31
- deploy snapshots
- Fix Cpuid1Ecx feature parsing for AMD CPUs.
- Fix a bug in the IsolateArgumentParser.
- Preprocess `_MSC_FULL_VER` to detect `cl.exe` version info.
- Drop redundant architecture error for Windows.
- Mark `skipLineIfHasNext` as static.
- [GR-51612] Assertion error when internal resource cache is overriden by the polyglot.engine.resourcePath system property.
- Use unsigned monitor and identity hash offsets and guarantee (not assert) that they are valid.
- update JVMCI to 23.1-b32
- Fix identity hash offset assertion
- Always apply JVMTI-related substitutions.
- Adhere to naming convention and add missing `onlyWith`.
- Update windows devkit for jdk21 to VS2022-17.6.5+1
- Correctly print JSON values in agent trace files.
- Support access-filter-file for native-image-configure.
- Minor fixes and cleanups.
- fix coding style
- deploy snapshots
- Use a common ThreadStartRoutinePrologue on all platforms.
- Aarch: Add means for post-processing code after emitting from LIR.
- Fix a Windows-specific thread handle leak.
- Avoid deadlocks when the VM is out-of-memory and other threading-related fixes.
- [GR-50823] Fix stamp inversion for ZeroExtend and SignExtend operations.
- [GR-50823] Unittests for stamp inversion during conditional elimination.
- [GR-50823] Infer input msb during stamp inversion for integer SignExtend.
- [GR-50823] Incorporate the bounds of stampToInvert when calculating the bounds of the inverted stamp.
- Use ModuleFinder to collect names of application modules
- Remove pre-python 3 support code
- Fix SyntaxWarning: invalid escape sequence '\.'
- Log when NFI unloads libraries
- Return a deterministic value on exception in native closure
- Fix UnsupportedMessageException exceptions in Sulong with a non-AbstractTruffleException cause
- Add TruffleEnv.exceptionCheck() in NFI to check for pending exceptions
- Remove bool workaround for old Windows compilers
- Add checks for recently started threads without Thread object.
- Substitute synchronized NullPointerException.fillInStackTrace which is not permitted in VMOperation.
- prevent macronodes in deoptimization targets
- Invocation profiles are not needed for JIT compilation
- induction variables: only non overflowing constant properties should be considered constant properties
- guard against deleting canonicalizer replacement.
- Add regression test
- Remove modules from -imagemp that are already provided by other means
- Remove debug code
- On Windows jdk native library jimage does not depend on stdc++
- Building driver into image requires JRTFileSystem support
- Fix return type of substituted method
- Ensure libstdc++ gets statically linked into agents
- Implement -H:+StaticLibStdCpp and use if for building the agents
- Ensure `ModuleFinder.of` and `ImageReader.open` are not used when imageModulePath is empty
- Only use full driver build args when building the driver image
- Remove obsolete agent-based image build code.
- Ensure jimage static jdk library get statically linked
- Do not allow jdk.internal.jimage.NativeImageBuffer at image-runtime
- Checkstyle fix
- Factor out common use of `dynamicLibC || staticLibCpp`
- Note removal of native-image-agent `build`-option in CHANGELOG
- remove unsupported jobs
- remove wasm gate jobs are it's experimental
- remove python gate job
- migrate truffle jobs to OracleJDK21
- sync
- remove sdk job gate based on Oracle JDK17
- migrate jobs to use labsjdk-ce-21
- remove jobs running on labsjdk-17
- remove unsupported espresso jobs
- fix common.json
- Properly catch exceptions during shutdown.
- remove candidate sulong jobs
- revert needed changes
- Make segfault handler more robust.
- Fix failure when no resource bundle nullary constructor is present
- process repeatable ExportMessage annotations for interop nodes
- simplify processing repeatable annotations
- improve readability of generated interop nodes by splitting up in target message name and exported method name and capitalize where appropriate
- use method element to construct targetMethodName to avoid passing argument
- use exported message name to construct super class name
- Don't try to incorrectly move virtual state inputs out of loops
- graph order: run some form of schedule verification in all tiers if possible
- Fix MacOS-specific perf data issue.
- ensure CompilationResult.methods does not contain duplicates
- [GR-51438] [GR-51888] Backport to 23.1: Don't rethrow internal parser errors as SyntaxError.
- Fix a deadlock in IsolateAwareTruffleCompiler.tearDownIsolateOnShutdown.
- Execute LogManager shutdown hook after all other shutdown hooks.
- fix enumerator : remove check on removed sulong gates
- restore needed wasm jobs and remove jdk17 based one
- Sync ci/ci_common/common.jsonnet file
- revert used JDK for gate-truffle-javadoc
- remove unsed labsjdk20 and labsjdk19 vars
- restore native-image job
- Add CompilationIsolateOptions.
- Parse compilation isolate arguments even if ParseRuntimeOptions is disabled.
- [GR-51744] Backport to 23.1: Fix possible infinite recursion in AbstractJSObjectArray.setElementImpl.
- Disable MethodHandle inlining blocking.
- Disable profiling of guard-with-test method handles
- Eagerly initialize VarHandle objects before method handle intrinsification
- Allow recursive inlining during method handle intrinsification
- Allow concrete subtypes of MethodHandle and VarHandle as parameters when folding reflection methods
- Changelog entry
- Disable failing assertion
- Workaround for a build-time crash.
- Improve uncaught exception handler and error handling in CEntryPointSnippets.initializeIsolate().
- Build GraalVM on Big Sur
- Add new darwin-aarch64 gates back
- Allow sulong gate to run on big sur
- Don't optimize away Narrow in comparisons with mixed signedness
- Add option ImplicitExceptionWithoutStacktraceIsFatal.
- Update JVMCI to 23.1-b34
- Update JVMCI to 23.1-b35 (21.0.3+5)
- Backport to 23.1: Do not inline ThrowableTracer#traceError.
- loop fragment: ensure we are not killing control flow when we have nodes in head/tail counted position that are actually empty themselves (skipable)
- Make ContextPolicyTest#testOptionDescriptorContextReuse more robust.
- fixed read nodes must only be removed if they are not used as null checks
- Introduce PolyglotInstrument#readyForContextEvents
- Adapt fix
- switch aarch64registerconfig to check for darwin instead of not darwin.
- Make options engine.CompilerThreads and engine.CompilationFailureAction available under UNTRUSTED sandbox policy.
- Update JVMCI to 23.1-b36
- [GR-52325] Backport to 23.1: Deopt loops in NetSuite JS code.
- Run the PureNFATransitionGenerator in reverse for lookbehinds
- Always involve both caretsOnPath and dollarsOnPath when deduplicating
- In complex empty check flavors, build quantifier guards also in DFA mode
- Pop guards and CG events using stack marks
- Reduce trivial and impossible guards when building DFA
- When buildingDFA, use deduplication instead of insideLoops to ensure termination
- Style fixes
- Add documentation for recent changes in NFATraversalRegexASTVisitor [GR-52425][GR-52428]
- TRegex: fix internal inconsistencies between matching modes
- TRegex: fix final state transition precedence in simpleCG mode
- TRegex: remove redundant condition in DFAGenerator
- Remove unsound quantifier reduction in OracleDBRegexParser
- Fix the calculation of enclosedCaptureGroups when wrapping groups
- Use quantifier's zeroWidthIndex, not the guard's index
- Disable empty checks monitor capture groups for OracleDB
- Passing all OracleDBTests now
- Restore JavaScript support in NFATraversalRegexASTVisitor
- Fix references to checkEmptyMatch in comments [GR-52429]
- TRegex: fix various parser bugs [GR-52430]
- TRegex: update OracleDB unit tests

### CODE REVIEW

**Comment by jerboaa** [comment]
Quarkus build fails with:

```
 Error:  Failed to execute goal on project quarkus-vertx-http-deployment: Could not resolve dependencies for project io.quarkus:quarkus-vertx-http-deployment:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT (absent): Could not find artifact io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project quarkus-vertx-http-deployment: Could not resolve dependencies for project io.quarkus:quarkus-vertx-http-deployment:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT (absent): Could not find artifact io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT
```

**Comment by jerboaa** [comment]
> Quarkus build fails with:
> 
> ```
>  Error:  Failed to execute goal on project quarkus-vertx-http-deployment: Could not resolve dependencies for project io.quarkus:quarkus-vertx-http-deployment:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT (absent): Could not find artifact io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project quarkus-vertx-http-deployment: Could not resolve dependencies for project io.quarkus:quarkus-vertx-http-deployment:jar:999-SNAPSHOT: The following artifacts could not be resolved: io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT (absent): Could not find artifact io.quarkus:quarkus-resteasy-reactive-server-spi-deployment:jar:999-SNAPSHOT
> ```

This seems resolved.

The remaining issue is Mandrel IT which is tracked here:
https://github.com/Karm/mandrel-integration-tests/issues/250

**Review by jerboaa — APPROVED** [review]
Seems OK.

**Comment by jerboaa** [comment]
@zakkak Could we get this merged, please?

**Comment by zakkak** [comment]
@jerboaa it looks like there are some more backports available upstream. Do you prefer merging this PR and creating a new one or updating this?

**Comment by jerboaa** [comment]
> @jerboaa it looks like there are some more backports available upstream. Do you prefer merging this PR and creating a new one or updating this?

Merging and a new one if possible. Thanks!

**Pull request merged**
