### PR TITLE
Do not raise an error if incomplete classpath is allowed

### PR DESCRIPTION
**Pull request by galderz**
Simple fix for #2556 for 20.1 branch. 

Original fix brings in more than what's needed for 20.1 branch, so fixing if condition check individually.

### CODE REVIEW

**Review by zakkak — APPROVED** [review]

**Comment by galderz** [comment]
@christianwimmer @olpaw Can you help fix OCA? It's not recognising my work email.

**Comment by olpaw** [comment]
> @christianwimmer @olpaw Can you help fix OCA? It's not recognising my work email.

@dougxc graalvmbot seems to have a problem understanding that @galderz OCA also extends to committing into `graalvm:mandrel/20.1`. What needs to be done to fix this?

**Comment by olpaw** [comment]
@galderz it seems you haven used galder -(at)- redhat -(dot)- com before in your PRs. I will add this email address to the allowed-list.

**Comment by olpaw** [comment]
@galderz I added your redhat EMail Address.

**Comment by zakkak** [comment]
Thank you @olpaw

**Comment by galderz** [comment]
Thx @olpaw @zakkak

**Pull request merged**
