### PR TITLE
Backport c++ compatible mangling support to 22.3

### LINKED ISSUE #432: Consider backport of c++ compatible mangling support for 22.3
Debugging experience in 22.3 tree isn't great. See https://github.com/oracle/graal/issues/5064#issuecomment-1272985630

We should consider a backport of https://github.com/oracle/graal/pull/5172 to 22.3 or find the right commits which broke the debuginfo test. I'm slightly in favor of the former.

### PR DESCRIPTION
**Pull request by zakkak**
Backports: https://github.com/oracle/graal/pull/4950
Closes: #432

### CODE REVIEW

**Comment by jerboaa** [comment]
The fix being present should also be verifiable by recently merged integration test here: https://github.com/Karm/mandrel-integration-tests/pull/122 That is the existing 22.3 branch should fail prior and pass after.

**Comment by jerboaa** [comment]
In fact, the 22.3 failure here from the nightly CI is because of this missing backport: https://github.com/graalvm/mandrel/actions/runs/3270318066/jobs/5378993901#step:10:18540

**Comment by jerboaa** [comment]
This mandrel IT test failure is fixed with #444:

```
Error:  Failures: 
Error:    AppReproducersTest.imageioAWTTest:429->imageioAWT:546 A different set of static libraries was expected. 
Expected: [libawt.a, libawt_headless.a, libfdlibm.a, libfontmanager.a, libjava.a, libjavajpeg.a, libjvm.a, liblcms.a, liblibchelper.a, libnet.a, libnio.a, libzip.a]
Actual:   [libawt.a, libawt_headless.a, libfdlibm.a, libfontmanager.a, libjava.a, libjavajpeg.a, libjvm.a, liblcms.a, liblibchelper.a, libmanagement_ext.a, libnet.a, libnio.a, libzip.a] ==> expected: <true> but was: <false>
[INFO] 
Error:  Tests run: 18, Failures: 1, Errors: 0, Skipped: 5
```

**Comment by jerboaa** [comment]
There were two failing test. One looking like a network glitch, the second as mentioned in https://github.com/graalvm/mandrel/pull/445#issuecomment-1282262268.

**Review by jerboaa — APPROVED** [review]
Running mandrel integration tests with this patch and #444 pass for me locally. 2 failures without those patches. LGTM.

**Review by adinn — COMMENTED** [review]
This looks good to me. I applied the patch to Mandrel 22.3 spun it up and checked the results and it seems to work ok.

One question before I ack it though. Did the upstream patches apply cleanly or did you make some tweaks. If the latter then what precisely?

**Comment by zakkak** [comment]
> This looks good to me. I applied the patch to Mandrel 22.3 spun it up and checked the results and it seems to work ok.
> 
> One question before I ack it though. Did the upstream patches apply cleanly or did you make some tweaks. If the latter then what precisely?

Thank you for the review @adinn !

The only conflict was in https://github.com/oracle/graal/blob/824967bfa15973848c05e4012798dc245e8f86b5/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionFeature.java#L232-L238

Due to https://github.com/oracle/graal/commit/dc932e594f1bb1dd7fbf2db5e40f0b18aeda7067 not being part of 22.3

**Comment by adinn** [comment]
@zakkak ^^^

**Comment by adinn** [comment]
> The only conflict was in https://github.com/oracle/graal/blob/824967bfa15973848c05e4012798dc245e8f86b5/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/reflect/ReflectionFeature.java#L232-L238
> 
> Due to https://github.com/oracle/graal/commit/dc932e594f1bb1dd7fbf2db5e40f0b18aeda7067 not being part of 22.3

Ok, that looks fine then!

**Review by adinn — APPROVED** [review]

**Pull request merged**
