### PR TITLE
Sync upstream release/graal-vm/22.3 branch with mandrel/22.3

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by jerboaa** [comment]
Looks like this returns `null` producing a GHA failure on the clone?

```
VERSION=$(jq -r .mx_version ${MANDREL_REPO}/common.json)
```

https://github.com/graalvm/mandrel/actions/runs/3928912464/jobs/6717082545#step:4:30

**Comment by jerboaa** [comment]
Mandrel IT failure:

```
Error:    JFRTest.jfrOptionsSmokeTest:193->jfrOptionsSmoke:331 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.JFRTest/jfrOptionsSmokeTest/build-and-run.log and check these offending lines: 
[warn][jfr,system] Exception occurred during execution of period hook for jdk.ContainerConfiguration(21191) ==> expected: <true> but was: <false>
Error:    JFRTest.jfrSmokeTest:107->jfrSmoke:171 build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/runner/work/mandrel/mandrel/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.JFRTest/jfrSmokeTest/build-and-run.log and check these offending lines: 
[warn][jfr,system] Exception occurred during execution of period hook for jdk.ContainerConfiguration(21312) ==> expected: <true> but was: <false>
```

Is caused by missing backport of:
https://github.com/oracle/graal/pull/5525 which is expected to be part of a later upstream sync.

**Comment by zakkak** [comment]
Mandrel integration tests are failing with:
```
[warn][jfr,system] Exception occurred during execution of period hook for jdk.ContainerConfiguration(21218) ==> expected: <true> but was: <false>
```
which will be fixed by https://github.com/oracle/graal/pull/5525

Rerunning Q IT Data1 since it failed due to some network issue. Overall things look good.

**Comment by jerboaa** [comment]
@zakkak Could you please merge this (github tells me there are conflicts though)? If there are more changes from upstream we can do another merge PR, right? Thoughts?

**Pull request merged**
