### PR TITLE
[23.0] Synchronization with upstream 23.0 branch for July CPU release

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by zakkak** [comment]
The mandrel integration tests are https://github.com/Karm/mandrel-integration-tests/issues/160

The interesting part though is that in the 23.0 branch the [single compile unit patch](https://github.com/oracle/graal/pull/6419) is not present, so we can't backport just https://github.com/oracle/graal/pull/6937. We will probably need a number of backports to get this fixes in 23.0.

**Comment by jerboaa** [comment]
> The interesting part though is that in the 23.0 branch the [single compile unit patch](https://github.com/oracle/graal/pull/6419) is not present, so we can't backport just [oracle#6937](https://github.com/oracle/graal/pull/6937). We will probably need a number of backports to get this fixes in 23.0.

Right. Yes, this will need to be considered. Lets wait and see how the fix develops in head first, though.

**Review by jerboaa — APPROVED** [review]

**Comment by adinn** [comment]
> The interesting part though is that in the 23.0 branch the https://github.com/oracle/graal/pull/6419 is not present, so we can't backport just https://github.com/oracle/graal/pull/6937. We will probably need a number of backports to get this fixes in 23.0.

Ah, so if the single compile unit patch (#6419) is not present in 23.0 then why do we want to backport #6937? As far as I am aware, the debug info generated prior to #6419 was not suffering from startup delays. Are there features provided by #6419 or dependent follow-ups that we need?

**Comment by jerboaa** [comment]
> > The interesting part though is that in the 23.0 branch the [oracle#6419](https://github.com/oracle/graal/pull/6419) is not present, so we can't backport just [oracle#6937](https://github.com/oracle/graal/pull/6937). We will probably need a number of backports to get this fixes in 23.0.
> 
> Ah, so if the single compile unit patch ([oracle#6419](https://github.com/oracle/graal/pull/6419)) is not present in 23.0 then why do we want to backport [oracle#6937](https://github.com/oracle/graal/pull/6937)?

We are seeing https://github.com/Karm/mandrel-integration-tests/issues/160 test failures in CI. See below.

> As far as I am aware, the debug info generated prior to [oracle#6419](https://github.com/oracle/graal/pull/6419) was not suffering from startup delays. Are there features provided by [oracle#6419](https://github.com/oracle/graal/pull/6419) or dependent follow-ups that we need?

See https://github.com/graalvm/mandrel/actions/runs/5620427175/job/15230467880#step:11:18570 it suggests https://github.com/Karm/mandrel-integration-tests/issues/160 being present in 23.0. I don't know why.

**Comment by zakkak** [comment]
Hmm, I was wrong the single unit PR is in 23.0 https://github.com/oracle/graal/commit/53072937bd22. False alarm!

**Comment by adinn** [comment]
> Hmm, I was wrong the single unit PR is in 23.0 https://github.com/oracle/graal/commit/53072937bd22

Ok, that was what I thought.

So, the difficulty with backporting #6937 (revert to CU per class) appears to be that 23.0 does not contain #6625 (debug info for foreign types). That is why it doesn't backport cleanly.

I don't know if backporting both PRs in sequence will apply but I think it is likely(or, at least, will only require minor tweaks). If so then do we want to backport both? Or do we instead backport a modified variant of the CU per class PR?

**Comment by zakkak** [comment]
I would say both. I will try to see how hard it is.

**Pull request merged**
