### PR TITLE
Unmark suites and bump version to 20.3.1.2

### PR DESCRIPTION
**Pull request by zakkak**
This PR was automatically generated by `mandrel-release.java` of graalvm/mandrel-packaging!

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Looks fine. Do we really need reviews for those changes?

**Comment by zakkak** [comment]
> Looks fine. Do we really need reviews for those changes?

No, not really. I will add an exception for the branches generated by the release script to allow them to be merged without a review.
I would still like all of us to get notified, so I am thinking about leaving the review requests in place. If you prefer something else let me know.

**Comment by zakkak** [comment]
> > Looks fine. Do we really need reviews for those changes?
> 
> No, not really. I will add an exception for the branches generated by the release script to allow them to be merged without a review.

Hmm the filter is based on the target branch and can't be configured based on the source branch, so it's not possible to have an exception here. We either need to disable the policy that enforces at least one review for each PR, or keep needing reviews for PRs like this as well.

**Comment by Karm** [comment]
Let's lift the requirement.  Whoever breaks the rule for anything else is buying and *shipping* beer to the others. The fees involved will suffice as a deterrent.

**Pull request merged**
