### PR TITLE
Implement annotation support for RecordComponents

### PR DESCRIPTION
**Pull request by zakkak**
Fix for https://github.com/oracle/graal/issues/3984 till it gets merged upstream.

### CODE REVIEW

**Comment by zakkak** [comment]
@jerboaa I tested this locally and seems to work as expected. I am going to merge it once CI is done if things look like before :)

**Comment by jerboaa** [comment]
> @jerboaa I tested this locally and seems to work as expected. I am going to merge it once CI is done if things look like before :)

Sounds good. Looks like Windows build issues are unrelated.

**Comment by jerboaa** [comment]
Thanks for doing this!

**Comment by zakkak** [comment]
> Sounds good. Looks like Windows build issues are unrelated.

Correct, https://github.com/graalvm/mandrel/pull/361 should take care of this.

**Pull request merged**
