### PR TITLE
Master cleaning

### PR DESCRIPTION
**Pull request by zakkak**
Final step towards Proposal 1 of https://oss.oracle.com/pipermail/graalvm-dev/2020-July/000071.html:

> Make the default branch contain only a README file explaining what Mandrel is, how it relates to Graal, and how to get your hands on it. This branch will also contain any workflows related to housekeeping, syncing branches, nightly testing, etc.
> This branch will not contain any code. So after git clone https://github.com/graalvm/mandrel and reading the README users will be asked to checkout another branch if they want to access the source code.

This PR removes all code from `master` and updates the readme and contributing files accordingly.
After approval I propose purging the `master` branch history (this will make `git clone` fast). 

PS: now is a good time to think about using a different (than `master`) branch as the default.

### CODE REVIEW

**Comment by fniephaus** [comment]
Wouldn't it be easier to just replace the current master with a fresh orphan branch?

**Comment by zakkak** [comment]
> Wouldn't it be easier to just replace the current master with a fresh orphan branch?

Yes it would, but it was not clear to me how to get it reviewed.

**Comment by fniephaus** [comment]
I was assuming you (or someone else from your team) has permissions to force push to this repository. You'll need that if you decide to purge the history. Instead, you could create a fresh orphan branch, e.g. "main" or force push directly to "master". Then open a PR against it for reviews. That way all these deleted files aren't part of the diff as well.

**Comment by zakkak** [comment]
> I was assuming you (or someone else from your team) has permissions to force push to this repository. 
Correct.
> You'll need that if you decide to purge the history.
Correct.
> Instead, you could create a fresh orphan branch, e.g. "main" or force push directly to "master". Then open a PR against it for reviews. That way all these deleted files aren't part of the diff as well.
Didn't know it would work this way, I'll give it a try. Thanks!

**Comment by zakkak** [comment]
@fniephaus it didn't work (and also closed the PR)

image

New PR available here https://github.com/graalvm/mandrel/pull/98

**Comment by fniephaus** [comment]
Well, you tried to open the PR against `graalvm:master` which you can't if the branch is an orphan. I was suggesting that you create a new orphan branch for Mandrel and open a PR against this new branch. Have a look at my fork (https://github.com/fniephaus/graal/) and the demo PR at https://github.com/fniephaus/graal/pull/1.

**Comment by zakkak** [comment]
Oh, I see. So I would get the review for the new branch and **then** force push it onto `master`. Thanks for the taking the time to make that clear for me @fniephaus :)

**Pull request closed without merging**
