### PR TITLE
New build type that allows testing without maven-deploy-local

### PR DESCRIPTION
**Pull request by zakkak**
As discussed in https://github.com/graalvm/mandrel/pull/574#issuecomment-1725625186

CI runs testing the change:

* build-type=mandrel-source: https://github.com/zakkak/mandrel/actions/runs/6245895538
* build-type=graal-source: https://github.com/zakkak/mandrel/actions/runs/6245896240
* build-type=mandrel-source-nolocalmvn: https://github.com/zakkak/mandrel/actions/runs/6245882692
* build-type=graal-source-nolocalmvn: https://github.com/zakkak/mandrel/actions/runs/6245894437

### CODE REVIEW

**Comment by jerboaa** [comment]
@zakkak I don't see a difference in the `mandrel-source` vs `mandrel-source-nolocalmvn` builds when it comes to a quarkus build. Both seem to skip downloading the mvn artefacts. Thoughts? It looks like the graalvm/mandrel build also doesn't build the local maven bits regardless.

**Comment by zakkak** [comment]
Yup, I mistyped the output variable's name as `maven-local-deploy` instead of `maven-deploy-local`....

**Comment by zakkak** [comment]
New CI runs:

- build-type=mandrel-source: https://github.com/zakkak/mandrel/actions/runs/6246296621
- build-type=graal-source: https://github.com/zakkak/mandrel/actions/runs/6246295918
- build-type=mandrel-source-nolocalmvn: https://github.com/zakkak/mandrel/actions/runs/6246298361
- build-type=graal-source-nolocalmvn: https://github.com/zakkak/mandrel/actions/runs/6246297527

**Update**: There's still something wrong

**Update2**: latest CI runs:

- build-type=mandrel-source: https://github.com/zakkak/mandrel/actions/runs/6246563662
- build-type=graal-source: https://github.com/zakkak/mandrel/actions/runs/6246694144
- build-type=mandrel-source-nolocalmvn: https://github.com/zakkak/mandrel/actions/runs/6246695066
- build-type=graal-source-nolocalmvn: https://github.com/zakkak/mandrel/actions/runs/6246696078

**Comment by jerboaa** [comment]
You seem to be building from a release tree, which doesn't include `SNAPSHOT` and thus, the maven version will be empty (yes, a pre-existing bug). See https://github.com/zakkak/mandrel/actions/runs/6246694144/job/16957799513#step:7:969

We probably need a smarter way to find the version. Maybe just use (assuming the 6'th token is the maven version that mx prints):
```
set $(head -n1 maven_deploy.log)
MAVEN_VERS=$(echo $6)
```

instead of:

```
MAVEN_VERS=$(for token in $(head -n1 maven_deploy.log); do if echo $token | grep -q 'SNAPSHOT'; then echo $token; fi; done)
```

**Comment by zakkak** [comment]
`MAVEN_VERS` issue should be fixed with https://github.com/graalvm/mandrel/commit/2eaa44475f28c99bca2c9feb2c7a8919127c7f0b

New CI runs (only for the cases that failed and I patched) :

- build-type=graal-source: https://github.com/zakkak/mandrel/actions/runs/6248464375
- build-type=mandrel-source-nolocalmvn: https://github.com/zakkak/mandrel/actions/runs/6247578254

**Review by jerboaa — APPROVED** [review]
LGTM (without the TEMP change to use your branch for `base.yml`)

**Pull request merged**
