### PR TITLE
2024-03-13 backports 17 sync

### PR DESCRIPTION
**Pull request by zakkak**
- respect maximum eden size in AggressiveShrinkCollectionPolicy.
- Improve OutOfMemoryError messages.
- Fixes issue-7652 for epsilon gc
- Remove broken method VMError.shouldNotReachHereAtRuntime().
- update to jvmci-23.0-b26
- Fix intrinsic frame states
- [GR-49481] Remove explicit null check exceptions from genCheckCast and genInstanceof.
- update to jvmci-23.0-b27
- Speedup method verification.
- GR-50540 : release GraalVM 23.0.3
- Remove Heap.allowPageSizeMismatch().
- Provide a method to set the physical memory size.
- New dev cycle GraalVM 23.0.4
- Use unsigned monitor and identity hash offsets and guarantee (not assert) that they are valid.
- [GR-48705] Fix stamp inversion for ZeroExtend and SignExtend operations.
- [GR-48705] Unittests for stamp inversion during conditional elimination.
- [GR-48705] Infer input msb during stamp inversion for integer SignExtend.
- Fix Cpuid1Ecx feature parsing for AMD CPUs.
- fix debug section alignment which can lead to corrupt debug info
- Add crash log output to exception handling.
- Catch exceptions that happen while a thread starts.
- Only use -H:Path validation in non-bundle mode
- Explain reasoning as comment
- update to jvmci-23.0-b28
- [GR-48705] Incorporate the bounds of stampToInvert when calculating the bounds of the inverted stamp.
- Fix a bug in the IsolateArgumentParser.
- update to jvmci-23.0-b29
- Fix Thread.getStackTrace() right after Thread.start().
- [GR-50823] Fix stamp inversion for ZeroExtend and SignExtend operations.
- [GR-50823] Unittests for stamp inversion during conditional elimination.
- [GR-50823] Infer input msb during stamp inversion for integer SignExtend.
- [GR-50823] Incorporate the bounds of stampToInvert when calculating the bounds of the inverted stamp.
- Preprocess `_MSC_FULL_VER` to detect `cl.exe` version info.
- Drop redundant architecture error for Windows.
- Mark `skipLineIfHasNext` as static.
- Add memory barrier to HeapImpl.getAllClasses().
- Crash log improvements.
- Minor fixes and cleanups.
- Adapt fix to 23.0
- Correctly print JSON values in agent trace files.
- Support access-filter-file for native-image-configure.
- update to jvmci-23.0-b30
- Fix identity hash offset assertion
- fix style issue
- update VSCode version
- induction variables: only non overflowing constant properties should be considered constant properties
- Use a common ThreadStartRoutinePrologue on all platforms.
- Fix a Windows-specific thread handle leak.
- Adapt fix to 23.0
- Avoid deadlocks when the VM is out-of-memory and other threading-related fixes.
- Add checks for recently started threads without Thread object.
- Substitute synchronized NullPointerException.fillInStackTrace which is not permitted in VMOperation.
- guard against deleting canonicalizer replacement.
- regression test
- Adapt fix to 23.0
- [GR-51110] Could not load library @rpath/libjsig.dylib for nodejs native standalone on GraalVM for JDK17.
- Don't try to incorrectly move virtual state inputs out of loops
- graph order: run some form of schedule verification in all tiers if possible
- Properly catch exceptions during shutdown.
- Constant fold reflection lookups in sun.nio.ch.Reflect
- Fix MacOS-specific perf data issue.
- Fix a deadlock in IsolateAwareTruffleCompiler.tearDownIsolateOnShutdown.
- Remove GU catalogs for CE
- ensure CompilationResult.methods does not contain duplicates
- Workaround for a build-time crash.
- update to jvmci-23.0-b31
- Don't optimize away Narrow in comparisons with mixed signedness
- update to jvmci-23.0-b32
- Allow TRegex to be used in SandboxPolicy.UNTRUSTED.
- loop fragment: ensure we are not killing control flow when we have nodes in head/tail counted position that are actually empty themselves (skipable)
- Workarounds for wrong class initialization configuration in microservice frameworks
- fixed read nodes must only be removed if they are not used as null checks
- Make segfault handler more robust.
- Adapt fix
- Improve uncaught exception handler and error handling in CEntryPointSnippets.initializeIsolate().
- Add option ImplicitExceptionWithoutStacktraceIsFatal.
- [GR-52326] Backport to 23.0: Deopt loops in NetSuite JS code.
- update to jvmci-23.0-b33

### CODE REVIEW

**Comment by jerboaa** [comment]
Thanks. And there is smoke:

```
 Produced artifacts:
 /home/runner/work/mandrel/mandrelvm/lib/svm_err_b_20240313T115439.804_pid3313.md (build_info)
========================================================================================================================
Failed generating 'libnative-image-agent' after 1m 6s.

The build process encountered an unexpected error:

> com.oracle.svm.core.util.VMError$HostedError: InternalFeature defined by com.oracle.svm.hosted.image.NativeImageDebugInfoFeature unexpectedly failed with a(n) java.lang.NullPointerException

Please inspect the generated error report at:
/home/runner/work/mandrel/mandrelvm/lib/svm_err_b_20240313T115439.804_pid3313.md

If you are unable to resolve this problem, please file an issue with the error report at:
https://graalvm.org/support
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1712)
	at build.buildAgents(build.java:230)
	at build.main(build.java:212)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1701)
	at build.buildAgents(build.java:230)
	at build.main(build.java:212)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:419)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
Error: Process completed with exit code 1.
```

**Comment by zakkak** [comment]
This is related to our backport https://github.com/graalvm/mandrel/pull/545

**Comment by zakkak** [comment]
> This is related to our backport #545

I missed a line while resolving a merge conflict. Fixed.

**Comment by jerboaa** [comment]
Remaining issues are:
- https://github.com/quarkusio/quarkus/issues/39322 solved with https://github.com/quarkusio/quarkus/pull/39372 (a re-run should see this fixed).
- Mandrel IT issue tracked here: https://github.com/Karm/mandrel-integration-tests/issues/250

**Review by jerboaa — APPROVED** [review]
Seems OK.

**Comment by jerboaa** [comment]
@zakkak Could we get this merged please? Thanks!

**Comment by zakkak** [comment]
@jerboaa it looks like there are some more backports available upstream. Do you prefer merging this PR and creating a new one or updating this?

**Comment by jerboaa** [comment]
@zakkak Please merge and create a new one with the rest of the changes. Thanks!

**Pull request merged**
