### PR TITLE
Migrate Collector to prod [default]

### PR DESCRIPTION
**Pull request by Karm**

### CODE REVIEW

**Comment by Karm** [comment]
```
2024-01-24T12:41:59.9450147Z [ERROR] Unresolveable build extension: Plugin io.quarkus:quarkus-maven-plugin:999-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact io.quarkus:quarkus-maven-plugin:jar:999-SNAPSHOT @ 
```

Hmm, not sure why this pops up in what is labeled as Q 3.2 M23.0.    Looks like mvn install is needed but hten again, this is not `main`....

**Comment by zakkak** [comment]
> ```
> 2024-01-24T12:41:59.9450147Z [ERROR] Unresolveable build extension: Plugin io.quarkus:quarkus-maven-plugin:999-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact io.quarkus:quarkus-maven-plugin:jar:999-SNAPSHOT @ 
> ```
> 
> Hmm, not sure why this pops up in what is labeled as Q 3.2 M23.0. Looks like mvn install is needed but hten again, this is not `main`....

@Karm Q 3.2 means we are building from [branch 3.2](https://github.com/quarkusio/quarkus/tree/3.2) which results in 

```
  elif ! $(expr match "$QUARKUS_VERSION" "^.*\.\(Final\|CR\|Alpha\|Beta\)[0-9]\?$" > /dev/null)
  then
    export QUARKUS_VERSION="999-SNAPSHOT"
  fi
```
being run, but 3.2 is actually using [3.2.999-SNAPSHOT](https://github.com/quarkusio/quarkus/blob/3c8c772dda9ed99674c9d8a6cd9cb4635d1ce5a2/build-parent/pom.xml#L8)

I am curious how it used to work till now (cached artifacts?)

**Comment by Karm** [comment]
@zakkak  @jerboaa  Switched Collector URLs now.

**Comment by Karm** [comment]
> I am curious how it used to work till now (cached artifacts?)

Sounds very plausible.

**Comment by zakkak** [comment]
I created https://github.com/graalvm/mandrel/pull/673 to resolve this. It will also require some changes on the mandrel-integration-tests side (according to https://github.com/graalvm/mandrel/issues/501#issue-1684434553).

**Pull request merged**
