### PR TITLE
[24.1] October CPU sync

### PR DESCRIPTION
**Pull request by zakkak**
Merge upstream changes from [`vm-24.1.1` tag](https://github.com/oracle/graal/releases/tag/vm-24.1.1).

- Avoid getHostBackend when instantiating UnimplementedGraalIntrinsics.
- [GR-57295] Aarch: Move setConservativeLabelRange after resetting crb.
- [GR-56104] Fix --bundle-create option and bundle-launcher feature on Windows.
- Start 24.1.1 dev cycle.
- Update js and graalpython imports.
- Update GraalVM versions used by simplelanguage and simpletool.
- Do not include TruffleJfrFeature if PGO config is specified.
- Eagerly initialize caches in ValueConversions
- Reset Provider.Service.constructorCache field
- Fix Addr part alignment in Truffle compilation logs.
- update JVMCI to 23.0.1+9-jvmci-b01
- Prevent emission of typeReachable in reachability-metadata.json
- Ensure correct condition format during metadata emission
- Parse constant resource patterns as globs
- Enable "type" to register reflective elements unconditionally when parsing in the agent or configure tool
- Pretty print legacy configuration files
- Add changelog entry for reachability-metadata.json
- [GR-57970] Backport to 24.1: Make js.webassembly option stable.
- [GR-57799] Backport to 24.1: Deprecate exposed truffle filesystem spi in VirtualFileSystem.
- update JVMCI to 23.0.1+10-jvmci-b01
- Remove constant memory buffer assumption and simplify ByteArrayWasmMemory.
- Check that memory 0 size >= initial size at the start of a wasm function.
- Only perform initial memory 0 bounds check if the wasm function uses memory 0.
- Work around for nullary benchmarkTeardownEach() in photon benchmark.
- Fix TraceTransferToInterpreter in WasmFunctionNode.profileCondition.
- Try to read WebAssembly.Module bytes via Buffer Interop.
- support different JDK version between CE and EE for labsjdk-latest
- deploy snapshots
- update JVMCI CE  to 23.0.1+10-jvmci-b01
- revert : support different JDK version between CE and EE for labsjdk-latest
- Update mx import.
- [GR-57721] Backport to 24.1: Create Gradle plugin with similar features as our Maven plugin.
- labsjdk respin : adopt jdk-23.0.1+11
- [GR-57975] Backport to 24.1: Update bouncycastle dependency
- Release GraalVM 24.1.1.

The merge was clean, but there are two open issues for properly testing this branch:

1. https://github.com/graalvm/mx/issues/285
2. The branch depends on a newer JVMCI version which is not satisfied by JDK 23+37, which is still the latest build returned by https://api.adoptium.net/v3/binary/latest/23/ea/linux/x64/jdk/hotspot/normal/eclipse

### CODE REVIEW

**Comment by jerboaa** [comment]
I'll take a look tomorrow. Thanks!

**Comment by jerboaa** [comment]
Build fails with:

```
Exception in thread "main" java.lang.IllegalArgumentException: Version should be of the form MAJOR.MINOR.PATCH not 7.27.5.1
	at MxVersion.<init>(build.java:1536)
	at Mx.<init>(build.java:933)
	at build.main(build.java:62)
```

... which should be fixed with this backport https://github.com/graalvm/mandrel-packaging/pull/458

**Comment by jerboaa** [comment]
> 2\. The branch depends on a newer JVMCI version which is not satisfied by JDK 23+37, which is still the latest build returned by https://api.adoptium.net/v3/binary/latest/23/ea/linux/x64/jdk/hotspot/normal/eclipse

@zakkak Is this an actual problem? This PR builds fine for me on `23+37`.

```
native-image 23-beta 2024-09-17
OpenJDK Runtime Environment Mandrel-24.1.1.0-dev4f15dffa4267 (build 23-beta+37-ea)
OpenJDK 64-Bit Server VM Mandrel-24.1.1.0-dev4f15dffa4267 (build 23-beta+37-ea, mixed mode)
```

So does this block this PR from getting merged?

**Review by jerboaa — APPROVED** [review]
This seems fine.

**Comment by jerboaa** [comment]
I'd suggest trying to merge https://github.com/graalvm/mandrel-packaging/pull/458 and trigger another CI build with this.

**Comment by zakkak** [comment]
The CI is now fetching `23.0.1-beta+37-202410051216` and seems to build fine with that version (let's see what the integration tests will look like).

When building locally I was getting a JVMCI version mismatch with `23+37`, interesting that you don't get that :|

In any case, there is indeed nothing blocking this PR any more. Once the CI completes I will merge it (probably tomorrow morning) unless there is some major issue.

**Comment by zakkak** [comment]
CI failure is https://github.com/Karm/mandrel-integration-tests/issues/290 and is not related to this specific version.

**Comment by jerboaa** [comment]
Thanks!

**Pull request merged**
