### PR TITLE
Merge upstream changes into Mandrel 23.1 release branch

### PR DESCRIPTION
**Pull request by jerboaa**
A trivial merge which only includes the whitespace change discussed [here](https://github.com/graalvm/graalvm-community-jdk21u/pull/17#issuecomment-2312149662). Otherwise, this would be an empty diff.

After this merge only Mandrel-specific diffs are present in the release tree which aren't in the
upstream community-jdk21u repo.

### CODE REVIEW

**Review by zakkak — APPROVED** [review]

**Comment by jerboaa** [comment]
FYI, the remainder of the diff to the upstream repo is (all are Mandrel related, so I consider this the minimal diff):
https://paste.centos.org/view/5fd02453

**Comment by zakkak** [comment]
> FYI, the remainder of the diff to the upstream repo is (all are Mandrel related, so I consider this the minimal diff): https://paste.centos.org/view/5fd02453

I agree, the only things we need to apply upstream are the checkout github action version bump and the version bump of GraalVM itself.

**Comment by jerboaa** [comment]
> > FYI, the remainder of the diff to the upstream repo is (all are Mandrel related, so I consider this the minimal diff): https://paste.centos.org/view/5fd02453
> 
> I agree, the only things we need to apply upstream are the checkout github action version bump and the version bump of GraalVM itself.

OK.

**Comment by jerboaa** [comment]
> > FYI, the remainder of the diff to the upstream repo is (all are Mandrel related, so I consider this the minimal diff): https://paste.centos.org/view/5fd02453
> 
> I agree, the only things we need to apply upstream are the checkout github action version bump and the version bump of GraalVM itself.

Done with these:
https://github.com/graalvm/graalvm-community-jdk21u/pull/18
https://github.com/graalvm/graalvm-community-jdk21u/pull/19

**Pull request merged**
