### PR TITLE
[Backport] Method handle substitutions fix

### LINKED ISSUE #559: [23.1] Several Quarkus native IT tests fail due to new MethodHandle substitutions
## Description
The 23.1 branch of Mandrel doesn't include the fix for https://github.com/quarkusio/quarkus/issues/35508 which got fixed upstream with https://github.com/oracle/graal/pull/7262

We need that fix backported to the 23.1 branch.

### PR DESCRIPTION
**Pull request by jerboaa**
These two fixes got cherry-picked from upstream https://github.com/oracle/graal/pull/7262 which we need to fix several quarkus integration tests.

Closes: #559

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM. I suggest merging it for testing purposes and if upstream decides to backport the fix as well we can drop it with a rebase (or just let it be).

**Comment by jerboaa** [comment]
Thanks for the review. Will do. I'll wait for CI to finish before I merge.

**Comment by jerboaa** [comment]
The remaining IT Data 5 failure is: https://github.com/quarkusio/quarkus/issues/35676. Mandrel IT tests are mostly the experimental flags warnings dealt elsewhere.

**Comment by zakkak** [comment]
The upstream PR has been backported so I am rebasing mandrel/23.1 and dropping this change.

**Comment by jerboaa** [comment]
Thanks!

**Pull request merged**
