### PR TITLE
Opt out from using module path by default 

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by jerboaa** [comment]
@zakkak do we have a tracker issue to re-enable testing with the builder on module path (I think we should)?

**Comment by zakkak** [comment]
No we don't have one. I guess we should open it after merging :)

**Comment by jerboaa** [comment]
There seems to be one remaining item in rest-easy-jackson:

```
 ========================================================================================================================
GraalVM Native Image: Generating 'quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (19.8s @ 0.20GB)
 Version info: 'GraalVM 22.2.0-dev01cdd0ac Java 17 Mandrel Distribution'
 Java version info: '17.0.4-beta+6-202206100946'
 C compiler: cl.exe (microsoft, x64, 19.29.30145)
 Garbage collector: Serial GC
 4 user-specific feature(s)
 - io.quarkus.runner.AutoFeature
 - io.quarkus.runtime.graal.DisableLoggingAutoFeature
 - io.quarkus.runtime.graal.ResourcesFeature
 - org.graalvm.home.HomeFinderFeature: Finds GraalVM paths and its version number
java.lang.IllegalAccessError: class io.quarkus.runner.AutoFeature (in unnamed module @0x4c1f22f3) cannot access class com.oracle.svm.core.jdk.proxy.DynamicProxyRegistry (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk.proxy to unnamed module @0x4c1f22f3
```

**Comment by jerboaa** [comment]
> No we don't have one. I guess we should open it after merging :)

I've created: https://github.com/graalvm/mandrel/issues/389

**Comment by zakkak** [comment]
We agreed on merging this to get the ci running again even with some errors and opening separate issues to track the potential failures like the one mentioned above by @jerboaa

**Pull request merged**
