### PR TITLE
Support removal of java.net.Inet6Address.cached_scope_id in 11.0.14+1

### LINKED ISSUE #314: Mandrel 21.2 branch fails to build with 11.0.14-dev (Inet6Address missing cached_scope_id)
Building mandrel from the 21.2 branch (21.3 branch likely has the same issue) with OpenJDK 11.0.14 results in:

```
DEBUG [build] Launcher line AFTER: exec "${location}/../../../bin/java" -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -Dorg.graalvm.version="21.2.0.3-dev" -Dorg.graalvm.config="Mandrel Distribution" --upgrade-module-path ${location}/../../jvmci/graal.jar --upgrade-module-path ${location}/../../jvmci/graal.jar --add-modules org.graalvm.truffle,org.graalvm.sdk --module-path ${location}/../../truffle/truffle-api.jar:${location}/../../jvmci/graal-sdk.jar "${jvm_args[@]}" ${app_path_arg} "${cp_or_mp}" ${main_class} "${launcher_args[@]}"
DEBUG [build] Build native agents...
DEBUG [OperatingSystem] Execute [/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/bin/native-image, --macro:native-image-agent-library] in /disk/graal/upstream-sources/mandrel-packaging
[libnative-image-agent:28605]    classlist:   1,549.78 ms,  0.96 GB
--initialize-at-build-time without arguments has been deprecated and will be removed in GraalVM 22.0.
[libnative-image-agent:28605]        (cap):     863.06 ms,  0.96 GB
[libnative-image-agent:28605]        setup:   2,652.13 ms,  0.96 GB
[libnative-image-agent:28605]     analysis:  11,748.52 ms,  1.76 GB
Fatal error:com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchFieldException: cached_scope_id
	at com.oracle.svm.util.ReflectionUtil.lookupField(ReflectionUtil.java:114)
	at com.oracle.svm.util.ReflectionUtil.lookupField(ReflectionUtil.java:101)
	at com.oracle.svm.core.jdk.JNIRegistrationUtil.fields(JNIRegistrationUtil.java:104)
	at com.oracle.svm.hosted.jdk.JNIRegistrationJavaNet.registerInitInetAddressIDs(JNIRegistrationJavaNet.java:194)
	at com.oracle.svm.hosted.jdk.JNIRegistrationJavaNet.registerNetworkInterfaceInit(JNIRegistrationJavaNet.java:220)
	at com.oracle.svm.hosted.ReachabilityHandlerFeature.duringAnalysis(ReachabilityHandlerFeature.java:119)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:730)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:730)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
Caused by: java.lang.NoSuchFieldException: cached_scope_id
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at com.oracle.svm.util.ReflectionUtil.lookupField(ReflectionUtil.java:106)
	... 14 more
[libnative-image-agent:28605]      [total]:  16,161.01 ms,  1.76 GB
# Printing build artifacts to: /disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/macros/native-image-agent-library/../../../libnative-image-agent.build_artifacts.txt
```

Root cause seems to be [JDK-8216417](https://bugs.openjdk.java.net/browse/JDK-8216417) which is new in 11.0.14-dev

### PR DESCRIPTION
**Pull request by jerboaa**
OpenJDK 11.0.14+1 got a backport of [JDK-8216417](https://bugs.openjdk.java.net/browse/JDK-8216417) which
got backported to Oracle JDK 11.0.13 one release earlier. Thus, we can re-use the patch.

Backports https://github.com/oracle/graal/commit/0d398e42d7248b1209396e28e88feb819a5a82be from https://github.com/oracle/graal/pull/3562

Closes #314

### CODE REVIEW

**Comment by jerboaa** [comment]
@zakkak PTAL

**Comment by jerboaa** [comment]
> LGTM, but I suggest we wait for 11.0.14-ea upstream builds to get this through our CI as well

Sounds good.

**Comment by jerboaa** [comment]
> > LGTM, but I suggest we wait for 11.0.14-ea upstream builds to get this through our CI as well
> 
> Sounds good.

@zakkak It's there now. https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.14%2B1

**Comment by zakkak** [comment]
Thanks for the heads up @jerboaa 

Being tested in https://github.com/graalvm/mandrel/actions/runs/1425306776

**Comment by jerboaa** [comment]
> Thanks for the heads up @jerboaa
> 
> Being tested in https://github.com/graalvm/mandrel/actions/runs/1425306776

Looks good. The mandrel build didn't fail (it was previously the case).

**Pull request merged**
