### PR TITLE
Sync mandrel 20.3 with upstream graal 20.3 

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by zakkak** [comment]
Started https://github.com/graalvm/mandrel/actions/runs/1029964032 to test this with the latest workflows

**Comment by zakkak** [comment]
CI runs with Quarkus 1.11.7.Final appears to fail due to some issues with the GH workflow:
```
Caused by: java.lang.NullPointerException
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.resolveSettingsFile(BootstrapMavenContext.java:321)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getUserSettings(BootstrapMavenContext.java:180)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getEffectiveSettings(BootstrapMavenContext.java:241)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.isOffline(BootstrapMavenContext.java:218)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.newRepositorySystem(BootstrapMavenContext.java:648)
	at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRepositorySystem(BootstrapMavenContext.java:223)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.<init>(MavenArtifactResolver.java:124)
	at io.quarkus.bootstrap.BootstrapAppModelFactory.getAppModelResolver(BootstrapAppModelFactory.java:192)
```

Testing with 1.11 branch instead, which is how we used to test 20.3 anyway:
https://github.com/graalvm/mandrel/actions/runs/1033739119

Note that irrespective of 1.11.7.Final tag vs 1.11 branch an issue we have is that 20.3.3 "partially" (see https://github.com/oracle/graal/issues/3591) integrates the new version scheme resulting in the following Quarkus warning:
```
 Error:  [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
 ```
 
 FTR Mandrel 20.3.2 prints:
 ``` 
 GraalVM Version 20.3.2.0-Final (Mandrel Distribution) (Java Version 11.0.11+9)
```

while Mandrel 20.3.3-dev currently prints:
```
20.3.3.0-dev9c1d123 (Java Version 11.0.12-ea+6)
```

Once https://github.com/oracle/graal/issues/3591 gets resolved Mandrel 20.3.3-dev is expected to print something like:
```
native-image 20.3.3.0-dev9c1d123 Java 11 Mandrel Distribution  (Java Version 11.0.12-ea+6)
```

which will result in Quarkus failing to parse the version, so I am working on fixing this on Quarkus 1.11 branch.

**Comment by zakkak** [comment]
Reverting the version scheme changes seems the safest way since it doesn't require a new Quarkus release and will also ensure users of 1.11.7.Final will automatically get the CPU update without any errors.

Regarding the CI failures the issue is fixed in #272

**Comment by zakkak** [comment]
All tests are passing!
https://github.com/graalvm/mandrel/actions/runs/1034694248

Going through the changes I see no red flags

**Comment by Karm** [comment]
@zakkak  Lemme run the Jenkins setup too before merging.

**Comment by Karm** [comment]
> @zakkak Lemme run the Jenkins setup too before merging.
Ad https://ci.modcluster.io/view/Mandrel/job/mandrel-20.3-linux-build/104/
@zakkak Integration TS looks fine, i.e. no non-whitelisted warnings.
Quarkus will keep running for next ~4 hours or so...

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by zakkak** [comment]
@Karm I see no [`mandrel-linux-integration-tests` job](https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-integration-tests/) trigger from [`mandrel-20.3-linux-build` 140](https://ci.modcluster.io/job/mandrel-20.3-linux-build/104/) :/

[`mandrel-linux-quarkus-tests` 354](https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-quarkus-tests/354/) shows some failures for both Q 1.11 and 2.0

Q 1.11.7.Final:
* Bouncy Castle JSSE
Logs: https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-quarkus-tests/354/LABEL=el8,MANDREL_VERSION=20.3,QUARKUS_VERSION=1.11.7.Final/consoleFull

Q 2.0.0.Final:
* Bouncy Castle JSSE
* Infinispan Client
* Main
* JPA - XML mapping - Modern app
* Container Image - Standard
* SmallRye Config
Logs: https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-quarkus-tests/354/LABEL=el8,MANDREL_VERSION=20.3,QUARKUS_VERSION=2.0.0.Final/consoleFull

Can you please have a look?
I was thinking about scheduling the same jobs to test `mandrel/20.3` to see if the failures are indeed related to the changes (which seems odd to me), WDYT?

**Review by Karm — APPROVED** [review]
@zakkak  That log is already replaced by newer runs. Perhaps I will make the history longer. I have the result downloaded though. BTW, I also run those Q 1.11.7.Final on Hydra and the result from the last night was just 1 failure *[1]* in 

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.182 s <<< FAILURE! - in io.quarkus.it.bouncycastle.BouncyCastleJsseITCase
[ERROR] io.quarkus.it.bouncycastle.BouncyCastleJsseITCase.testListProviders  Time elapsed: 0.011 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Unable to start native image in 60s
Caused by: java.lang.RuntimeException: Unable to start native image in 60s
```
  
 I re-ran it again on a dedicated server and the failure is the same both with

 ```
 GraalVM Version 20.3.2.0-Final (Mandrel Distribution) (Java Version 11.0.11+9)
 ```

 and with

 ```
 GraalVM Version 20.3.2.1-devf9f24ba465 (Mandrel Distribution) (Java Version 11.0.12-ea+6)
 ```
 
 and with
 
 ```
 GraalVM Version 20.3.3.0-dev2bf3e12d14 (Mandrel Distribution) (Java Version 11.0.12-ea+6)
 ```
 So I am giving this  PR :+1: 
 
 *[1]*
 TS runs with these exclusions:
 ```
             export MODULES="-pl \
!bouncycastle-fips-jsse,\
!devtools,\
!google-cloud-functions,\
!google-cloud-functions-http,\
!kubernetes-client,\
!kubernetes/maven-invoker-way,\
!maven"
```

**Comment by zakkak** [comment]
I have updated the PR new CI run: https://github.com/graalvm/mandrel/actions/runs/1038619053

**Comment by zakkak** [comment]
All tests passing on GH.

@Karm waiting for your green light to merge this.

**Comment by zakkak** [comment]
Tests on our Jenkins instance as well:
* [Quarkus tests](https://ci.modcluster.io/view/Mandrel/job/mandrel-linux-quarkus-tests/364/LABEL=el8,MANDREL_VERSION=20.3,QUARKUS_VERSION=1.11.7.Final/consoleFull)
  - `debugSymbolsSmokeGDB` fails, but debug symbols are created

* [Integration tests](https://ci.modcluster.io/job/mandrel-linux-integration-tests/421/LABEL=el8,MANDREL_VERSION=20.3,QUARKUS_VERSION=1.11.7.Final/)
  - `Bouncy Castle JSSE` fails
  
I see no new failures after the update of this PR so I am merging this

**Pull request merged**
